### ISSUE TITLE
Semantische HTML

### ISSUE THREAD

**Issue by DaanKorver** [RalphKocken/the-client-case#3]
https://github.com/RalphKocken/the-client-case/blob/c316fb8cfbe1e5e5c9a638348f7b0c47e29db261/index.html#L23-L26

Ik zie hier dat je gebruikt maakt van een div met daarin een ```h2``` en een ```img```. Het ziet er naar uit dat je dit gebruikt voor alle stekjes. Misschien zou je een ```ul``` kunnen gebruiken om er een lijst van te maken? En i.p.v. een ```div``` een ```section```?

**Comment by krijnhoetmer** [comment]
En als je dan toch bezig bent, ook meteen alle `<p>` elementen even als een `<ul>` met woorden ;)

**Comment by RalphKocken** [comment]
Lijst niet gemaakt, maar zou een optie kunnen zijn. Wel heb ik de "div" veranderd in section.
