### ISSUE TITLE
Alt attribuut bij images

### ISSUE THREAD

**Issue by krijnhoetmer** [RalphKocken/the-client-case#6]
Zorg, zeker bij logo's, voor goede `alt` attributen. Content images van goede alternatieve tekst voorzien is een stuk lastiger, maar voor logo's en interactieve elementen is het goed om het jezelf aan te leren.

Als je los wilt gaan op wat de HTML specificatie zegt over verschillende `alt` attributen in verschillende contexten, zie https://html.spec.whatwg.org/multipage/images.html#alt (maar er zijn een stuk meer tutorials te vinden).

https://github.com/RalphKocken/the-client-case/blob/0bc8b291ec0504d04160b883abec52a7ebcf462b/index.html#L12-L16

**Comment by RalphKocken** [comment]
Opgelost!
