### ISSUE TITLE
Serieus?! :)

### ISSUE THREAD

**Issue by krijnhoetmer** [RalphKocken/the-client-case#7]
Kun je die CSS border niet op een ander element erbij prakken? ;)

https://github.com/RalphKocken/the-client-case/blob/0bc8b291ec0504d04160b883abec52a7ebcf462b/index.html#L112

**Comment by RalphKocken** [comment]
Hehe.. je hebt gelijk. Opgelost door background-color te gebruiken ipv een hele ander div er om heen.
